
spring.application.name=SkanderBenmna4CCE10
# Connexion a la base de donnees
spring.datasource.url=jdbc:mysql://localhost:3306/autoloc_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true